version: "3.8"
services:
  postgres:
    image: timescale/timescaledb:2.14.2-pg16
    container_name: stabilisim-pg
    environment:
      - POSTGRES_USER=unknown
      - POSTGRES_PASSWORD=unknown
      - POSTGRES_DB=unknown
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stabilisim -d stabilisim"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: stabilisim-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: